#!/bin/bash

function fce_system {

echo '
<HTML>

<HEAD>

   <TITLE>Informace o systému</TITLE>
   <meta http-equiv="Content-Type"content="text/html; charset=utf-8">
   <meta http-equiv="content-Language" content="cs">

   <style type="text/css">

    pre{color: black; font: Arial; font-size: 12pt;}

   </style>

</HEAD>
 
<BODY>

   <BR>
   <font color="black" face="Arial" size="5">
   Informace o systému
   </font>

   <BR>
   <BR>

   <pre>'
inxi -S -c 0
echo '
   </pre> 

   <BR> 
   <BR>
   <BR>

</BODY>

</HTML>'
}
fce_system >system.html
