#!/bin/bash

function fce_keyboard {

echo '
<HTML>

<HEAD>

   <TITLE>Klávesnice</TITLE>
   <meta http-equiv="Content-Type"content="text/html; charset=utf-8">
   <meta http-equiv="content-Language" content="cs">

   <style type="text/css">

    pre{color: black; font: Arial; font-size: 12pt;}

   </style>

</HEAD>
 
<BODY>

   <BR>
   <font color="black" face="Arial" size="5">
   Klávesnice
   </font>

   <BR>
   <BR>

   <pre>'
hwinfo --short --keyboard
echo '
   </pre> 

   <BR> 
   <BR>
   <BR>

</BODY>

</HTML>'
}
fce_keyboard >keyboard.html
