#!/bin/bash

function fce_others {

echo '
<HTML>

<HEAD>

   <TITLE>Další informace</TITLE>
   <meta http-equiv="Content-Type"content="text/html; charset=utf-8">
   <meta http-equiv="content-Language" content="cs">

   <style type="text/css">

    pre{color: black; font: Arial; font-size: 12pt;}

   </style>

</HEAD>
 
<BODY>

   <BR>
   <font color="black" face="Arial" size="5">
   Další informace
   </font>

   <BR>
   <BR>

   <pre>'
inxi -s -I -c 0
echo
uname -a
echo '
   </pre> 

   <BR> 
   <BR>
   <BR>

</BODY>

</HTML>'
}
fce_others >others.html
