#!/bin/bash

function fce_zahl1 {

echo '
<html>

<head>

   <meta http-equiv="Content-Type"content="text/html; charset=utf-8">
   <meta http-equiv="content-Language" content="cs">

   <title>Zahlavi1</title>

   <style type="text/css">

	pre{color: black; font: Arial; color: #EDB169; font-weight: bold;}

   </style>

</head>

<body bgcolor="075D8C">
   <img src="obr1.png" align="left" width="44" height="52">
   <pre>'
   
date +"aktualizováno: %H:%M.%S"
echo 'uživatelem:' `hostname`
echo '
</pre>

</body>

</html>'
}
fce_zahl1 >zahlavi1.html
