#!/bin/bash

function fce_zahl1 {

echo '
<html>

<head>

   <meta http-equiv="Content-Type"content="text/html; charset=utf-8">
   <meta http-equiv="content-Language" content="cs">

   <title>Zahlavi1</title>

</head>

<pre>'
date +"aktualizováno: %H:%M.%S"
echo 'uživatelem:' `hostname`
echo '
</pre>

</html>'
}
fce_zahl1 >zahlavi1.html
